version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.46
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16685:16685
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318
  
  service1:
    build:
      context: ./service1
    ports:
      - 3001:3000
    environment:
      # - OTEL_TRACE_HOST=143.198.216.115
      - OTEL_TRACE_HOST=jaeger
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service1
  
  service2:
    build:
      context: ./service2
    ports:
      - 3002:3000
    environment:
      # - OTEL_TRACE_HOST=143.198.216.115
      - OTEL_TRACE_HOST=jaeger
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service2

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss:8.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning